name: "Position"
description: "template for the position cards"
assignees: "iqsilva"
labels: "Long Term Goal"
title: 💻
body:
  - type: markdown
    attributes:
      value: "## 🎯 What"
  - type: markdown
    attributes:
      value: "<describe the goal here>"
  - type: markdown
    attributes:
      value: "## ❤ Why?"
  - type: markdown
    attributes:
      value: "<why this is important>"
  - type: markdown
    attributes:
      value: "## 🧑‍🏫 Sponsors, Mentors, Collaborators"
  - type: markdown
    attributes:
      value: "<who can support you>"
  - type: markdown
    attributes:
      value: "## 📋 Actions"
  - type: textarea
    attributes:
      label: "To work towards this goal, I intend to:"

