name: Notify In Progress Items

on:
  schedule:
    - cron: '0 9 * * 1' # Executa toda segunda-feira às 9:00 UTC
  workflow_dispatch: # Permite disparo manual

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Project Items via GraphQL
      uses: octokit/graphql-action@v2.x
      id: get_items
      with:
        query: |
          query {
            viewer {
              projectV2(number: 4) {
                items(first: 100) {
                  nodes {
                    id
                    content {
                      __typename
                      ... on Issue {
                        url
                        title
                      }
                      ... on PullRequest {
                        url
                        title
                      }
                    }
                    fieldValues(first: 10) {
                      nodes {
                        ... on ProjectV2ItemFieldSingleSelectValue {
                          name
                          id
                        }
                      }
                    }
                  }
                }
              }
            }
          }
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}

    - name: Check and Send Notification via IFTTT
      run: |
        python - <<EOF
        import json
        import requests

        # Parse the JSON data from the GraphQL query output
        data = json.loads('''${{ steps.get_items.outputs.data }}''')

        # Filter items that have a field with the name "In Progress"
        in_progress_items = [
            item for item in data['viewer']['projectV2']['items']['nodes']
            if any(field.get('name') == "In Progress" for field in item['fieldValues']['nodes'])
        ]

        # Collect titles of the items in the "In Progress" column
        titles = [item['content']['title'] for item in in_progress_items]

        # Check if there are any items in the "In Progress" column
        if titles:
            # Format the titles into a single string
            titles_str = ", ".join(titles)
            
            # Send a notification via IFTTT
            requests.post(
                "https://maker.ifttt.com/trigger/notification_github/with/key/lg7s5PhDS4NWUXwbcdSAMoLyDchR0mstR_sIv2dkk-B",
                json={"value1": "In Progress Items", "value2": f"You have the following items to study today: {titles_str}"}
            )
        else:
            # Print a message if no items are found
            print("No items in 'In Progress' column.")
        EOF
